close all
clear all
clc

init

check('all', ~any(~[
	check('getR2', test_getR2, true),...
	check('costfunction', test_costfunction, true),...
	check('regLinearize', test_regLinearize, true),...
	check('standardError', test_standardError, true),...
	check('splitDataRandom', test_splitDataRandom, true),...
	check('trainlinear', test_trainLinear, true),...
	check('linreg', test_linreg, true),...
	check('logitReg', test_logitReg, true),...
	check('kernelReg', test_kernelReg, true),...
	check('calcreg', test_calcreg, true),...
	]), true)